---
- name: Converge
  hosts: all
  become: true
  collections:
    - community.general
  tasks:
    - name: Run role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
